meta_product_name: "Fit and Co"
meta_title: "Fit and Co - Salle de sport Talmont Saint Hilaire"
meta_description: "Découvrez Fit and Co, Espace musculation, cardio & cross training pour vous dépasser et vous surpasser.
Cours collectifs & vidéos. Ton Club de sport à Talmont Saint Hilaire !"
meta_image: "fitandcologo.png" # should exist in `app/assets/images/`

